---
name: Molecule test

on:
  push:
    branches:
      - master
  schedule:
    - cron: 34 3 * * 5

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: x64
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: Install dependencies
        run: ls -alh
      - name: Molecule
        run: molecule test
