---
name: Molecule test

on:
  push:
    branches:
      - master
  schedule:
    - cron: 34 3 * * 5

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: x64
      - name: Check docker
        run: |
          set -x
          docker version
          whoami
          docker run hello-world
      - name: Install dependencies
        run: make update-test
      - name: Molecule
        run: molecule --debug test
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add requirements.txt
          git add docs/newsletter
          git diff-index --quiet HEAD \
            || git commit -m "chore: update dependencies"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
